-- MySQL Script generated by MySQL Workbench
-- 06/28/16 20:09:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema is_kmeti_babic_primoz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema is_kmeti_babic_primoz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `is_kmeti_babic_primoz` DEFAULT CHARACTER SET utf8 ;
USE `is_kmeti_babic_primoz` ;

-- -----------------------------------------------------
-- Table `is_kmeti_babic_primoz`.`Uporabnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is_kmeti_babic_primoz`.`Uporabnik` (
  `idUporabnik` INT NOT NULL,
  `Ime` VARCHAR(45) NOT NULL,
  `Priimek` VARCHAR(45) NOT NULL,
  `Naslov` VARCHAR(45) NOT NULL,
  `Postna_St` VARCHAR(45) NOT NULL,
  `Mail` VARCHAR(45) NOT NULL,
  `Geslo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUporabnik`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `is_kmeti_babic_primoz`.`Oglas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is_kmeti_babic_primoz`.`Oglas` (
  `idOglas` INT NOT NULL,
  `Ime_O` LONGTEXT NULL,
  `Cena_O` INT NULL,
  `Kolicina_O` INT NULL,
  `Opis_O` LONGTEXT NULL,
  `Prodajalec_O` INT NOT NULL,
  PRIMARY KEY (`idOglas`),
  INDEX `fk_Oglas_Uporabnik1_idx` (`Prodajalec_O` ASC),
  FULLTEXT INDEX `Ime_O` (`Ime_O` ASC),
  CONSTRAINT `fk_Oglas_Uporabnik1`
    FOREIGN KEY (`Prodajalec_O`)
    REFERENCES `is_kmeti_babic_primoz`.`Uporabnik` (`idUporabnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `is_kmeti_babic_primoz`.`Narocilo_O`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is_kmeti_babic_primoz`.`Narocilo_O` (
  `Kupec_O` INT NOT NULL,
  `Oglas_idOglas` INT NOT NULL,
  `Narocilo_Cena_O` INT NULL,
  `Narocilo_Kolicina_O` INT NULL,
  `Narocilo_Datum_O` DATE NULL,
  `Obdelava_Datum_O` DATE NULL,
  `Obdelano_O` TINYINT(1) NULL,
  PRIMARY KEY (`Kupec_O`, `Oglas_idOglas`),
  INDEX `fk_Uporabnik_has_Oglas_Oglas1_idx` (`Oglas_idOglas` ASC),
  INDEX `fk_Uporabnik_has_Oglas_Uporabnik_idx` (`Kupec_O` ASC),
  CONSTRAINT `fk_Uporabnik_has_Oglas_Uporabnik`
    FOREIGN KEY (`Kupec_O`)
    REFERENCES `is_kmeti_babic_primoz`.`Uporabnik` (`idUporabnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uporabnik_has_Oglas_Oglas1`
    FOREIGN KEY (`Oglas_idOglas`)
    REFERENCES `is_kmeti_babic_primoz`.`Oglas` (`idOglas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `is_kmeti_babic_primoz`.`Novica`
-- -----------------------------------------------------



-- -----------------------------------------------------
-- Table `is_kmeti_babic_primoz`.`Priloga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is_kmeti_babic_primoz`.`Priloga` (
  `idPriloga` INT NOT NULL,
  `Slika` BLOB NOT NULL,
  `Novica_idNovica` INT NOT NULL,
  PRIMARY KEY (`idPriloga`),
  INDEX `fk_Priloga_Novica1_idx` (`Novica_idNovica` ASC),
  CONSTRAINT `fk_Priloga_Novica1`
    FOREIGN KEY (`Novica_idNovica`)
    REFERENCES `is_kmeti_babic_primoz`.`Novica` (`idNovica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `is_kmeti_babic_primoz`.`Kosarica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is_kmeti_babic_primoz`.`Kosarica` (
  `idKosarica` INT NOT NULL,
  `Ime_K` LONGTEXT NULL,
  `Cena_K` INT NULL,
  `Klicina_K` INT NULL,
  `Opis_K` LONGTEXT NULL,
  `Prodjajalec_K` INT NOT NULL,
  PRIMARY KEY (`idKosarica`),
  INDEX `fk_Kosarica_Uporabnik1_idx` (`Prodjajalec_K` ASC),
  FULLTEXT INDEX `Ime_K` (`Ime_K` ASC),
  CONSTRAINT `fk_Kosarica_Uporabnik1`
    FOREIGN KEY (`Prodjajalec_K`)
    REFERENCES `is_kmeti_babic_primoz`.`Uporabnik` (`idUporabnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `is_kmeti_babic_primoz`.`Narocilo_K`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `is_kmeti_babic_primoz`.`Narocilo_K` (
  `Narocnik_K` INT NOT NULL,
  `Kosarica_idKosarica` INT NOT NULL,
  `Cena_K` INT NULL,
  `Kolicina_K` INT NULL,
  `Datum_Narocila_K` DATE NULL,
  `Stevilo_Kosaric_Tedensko` INT NULL,
  `Datum_Zakljucka_K` DATE NULL,
  PRIMARY KEY (`Narocnik_K`, `Kosarica_idKosarica`),
  INDEX `fk_Uporabnik_has_Kosarica_Kosarica1_idx` (`Kosarica_idKosarica` ASC),
  INDEX `fk_Uporabnik_has_Kosarica_Uporabnik1_idx` (`Narocnik_K` ASC),
  CONSTRAINT `fk_Uporabnik_has_Kosarica_Uporabnik1`
    FOREIGN KEY (`Narocnik_K`)
    REFERENCES `is_kmeti_babic_primoz`.`Uporabnik` (`idUporabnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uporabnik_has_Kosarica_Kosarica1`
    FOREIGN KEY (`Kosarica_idKosarica`)
    REFERENCES `is_kmeti_babic_primoz`.`Kosarica` (`idKosarica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
